### ISSUE TITLE
Microbiology.md

### ISSUE THREAD

**Issue by Cosmyccc** [JohananOppongAmoateng/VetDataHub#3]
I would like to add bacteria dataset under Microbiology.md.

**Comment by JohananOppongAmoateng** [comment]
@Rani1303 please submit a pull request with your changes. Thank you

**Comment by Cosmyccc** [comment]
@JohananOppongAmoateng Can you mark this issue under hacktoberfest2024 and assign it to me?

**Comment by JohananOppongAmoateng** [comment]
@Rani1303 assigned you

**Comment by Cosmyccc** [comment]
Hey @JohananOppongAmoateng I have created a PR, can you please review it?

**Comment by JohananOppongAmoateng** [comment]
@Rani1303 merged your pull request

**Comment by Cosmyccc** [comment]
Hey @JohananOppongAmoateng, this PR is not reflecting in my Hacktoberfest dashboard. It is showing that this repository is not participating in Hacktoberfest, maintainers need to add hacktoberfest-accepted label. Please add the hacktoberfest-accepted label.

**Comment by JohananOppongAmoateng** [comment]
@Rani1303  added it
